### PR TITLE
Landing Page > Alumni Section > Responsiveness

### PR DESCRIPTION
**Pull request by Hgjnnf**
Screenshot 2023-09-06 211528
Screenshot 2023-09-06 211548

### CODE REVIEW

**Review by IcedTea2K — DISMISSED** [review]
At about 714x800, the carousel is partially obscured.
image

Also, on mobile, are we planning on removing the arrows and make the carousel draggable instead? Because right now there is no way to go to the next page in the carousel
image

**Comment by Hgjnnf** [comment]
> At about 714x800, the carousel is partially obscured.
> 
> image
> 
> 
> 
> Also, on mobile, are we planning on removing the arrows and make the carousel draggable instead? Because right now there is no way to go to the next page in the carousel
> 
> image
> 
> 

We're going to design for Large and small screens for now, so I think we can ignore this and leave it for later.

Yea, we're removing the arrows. It's not draggable either. Instead, it looks like the bottom button will take the user to see the alumni.

**Comment by Kevin-Tan25** [comment]
Small comment, could you make sure the margins match follow Figma pls?
Screen Shot 2023-09-13 at 10 19 59 PM

**Review by Kevin-Tan25 — APPROVED** [review]
LGTM

**Pull request merged**
